language: go

go:
  - 1.13.x
  - master

# Only clone the most recent commit.
git:
  depth: 1

script:
  - make
  - bin/tiptester

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bin/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    branch: master